FROM python:3.11

WORKDIR /bot

# 更新・日本語化
RUN apt-get update && apt-get install -y locales tzdata && \
    localedef -f UTF-8 -i ja_JP ja_JP.UTF-8 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:ja
ENV LC_ALL ja_JP.UTF-8
ENV TZ Asia/Tokyo
ENV TERM xterm

# pip install
COPY requirements.txt /bot/
RUN pip install --no-cache-dir -r requirements.txt

# アプリケーションコードのコピー
COPY . /bot

# ポート開放 (uvicornで指定したポート)
EXPOSE 2627

# 実行
CMD ["python", "app/main.py"]
